// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM85etqfiokYqQjMxIB83GrdrC5vgAUeY',
    appId: '1:756478174874:web:e12f17ed10ca7e94762123',
    messagingSenderId: '756478174874',
    projectId: 'finalvenety',
    authDomain: 'finalvenety.firebaseapp.com',
    storageBucket: 'finalvenety.appspot.com',
    measurementId: 'G-0XVN9HJX33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5H6R0VR_gG-RKChtBA7CYPFgV54_C2UU',
    appId: '1:756478174874:android:f14bed75f6a75d82762123',
    messagingSenderId: '756478174874',
    projectId: 'finalvenety',
    storageBucket: 'finalvenety.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSc2CpoM1fC3JDmxOUY8HfR4OneTd8fek',
    appId: '1:756478174874:ios:228cf8226390f20e762123',
    messagingSenderId: '756478174874',
    projectId: 'finalvenety',
    storageBucket: 'finalvenety.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSc2CpoM1fC3JDmxOUY8HfR4OneTd8fek',
    appId: '1:756478174874:ios:228cf8226390f20e762123',
    messagingSenderId: '756478174874',
    projectId: 'finalvenety',
    storageBucket: 'finalvenety.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM85etqfiokYqQjMxIB83GrdrC5vgAUeY',
    appId: '1:756478174874:web:674a380fe1888392762123',
    messagingSenderId: '756478174874',
    projectId: 'finalvenety',
    authDomain: 'finalvenety.firebaseapp.com',
    storageBucket: 'finalvenety.appspot.com',
    measurementId: 'G-2FZW4ZR7ZK',
  );
}
